<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class NominationSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nominations')->insert([
            [
                'nominee_name' => 'Nominee 1',
                'nominee_phone' => '098-765-4321',
                'nominee_email' => 'nominee1@example.com',
                'reason' => 'Exemplary leadership',
                'candidate_id' => 1,
                'org_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nominee_name' => 'Nominee 2',
                'nominee_phone' => '123-456-7890',
                'nominee_email' => 'nominee2@example.com',
                'reason' => 'Outstanding community service',
                'candidate_id' => 2,
                'org_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nominee_name' => 'Nominee 3',
                'nominee_phone' => '098-765-4321',
                'nominee_email' => 'nominee3@example.com',
                'reason' => 'Leadership',
                'candidate_id' => 3,
                'org_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nominee_name' => 'Nominee 4',
                'nominee_phone' => '098-765-4321',
                'nominee_email' => 'nominee4@example.com',
                'reason' => 'Leadership',
                'candidate_id' => 4,
                'org_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('candidates')->insert([
            [
                'candidate_name' => 'Candidate 1',
                'candidate_image' => 'candidate1.jpg',
                'candidate_phone' => '012-3456789',
                'candidate_email' => 'candidate1@example.com',
                'candidate_gender' => 'Male',
                'candidate_ic' => '901201-14-5567',
                'candidate_address' => '123 Main Street, Kuala Lumpur',
                'nationality' => 'Malaysian',
                'religion' => 'Islam',
                'job' => 'Software Engineer',
                'income' => 'RM 3000 - RM 4000',
                'marriage_status' => 'Single',
                'position' => 'President',
                'short_biography' => 'I am an experienced leader with over 10 years in community service, dedicated to making a positive impact in the lives of individuals and communities. Throughout my career, I have focused on building strong relationships and fostering collaboration among diverse groups to address social challenges and promote community well-being.',
                'manifesto' => 'Committed to technological advancement and community development.',
                'status' => 'Pending',
                'reason' => '',
                'sign' => 'candidate1.jpg',
                'votes_count' => 25,
                'user_id' => 2,
                'nominee_id' => json_encode([1, 2]),
                'cand_doc_id' => json_encode([1,2]),
                'election_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'candidate_name' => 'Candidate 2',
                'candidate_image' => '',
                'candidate_phone' => '019-8765432',
                'candidate_email' => 'candidate2@example.com',
                'candidate_gender' => 'Female',
                'candidate_ic' => '880315-14-5432',
                'candidate_address' => '456 Park Avenue, Petaling Jaya',
                'nationality' => 'Malaysian',
                'religion' => 'Buddhist',
                'job' => 'Business Consultant',
                'income' => 'RM 2000 - RM 3000',
                'marriage_status' => 'Married',
                'position' => 'Vice President',
                'short_biography' => 'I am a business strategist with a strong background in community leadership. Over the years, I have dedicated my career to helping organizations harness the power of community engagement to drive growth and innovation.',
                'manifesto' => 'Focus on economic growth and sustainable development. Our vision is to create a transparent, efficient, and inclusive society where technology empowers every citizen. We commit to enhancing',
                'status' => 'Pending',
                'reason' => '',
                'sign' => 'candidate2.jpg',
                'votes_count' => 15,
                'user_id' => 2,
                'nominee_id' => json_encode([3]),
                'cand_doc_id' => json_encode([3,4]),
                'election_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'candidate_name' => 'Candidate 3',
                'candidate_image' => '',
                'candidate_phone' => '019-8765432',
                'candidate_email' => 'candidate3@example.com',
                'candidate_gender' => 'Male',
                'candidate_ic' => '810315-14-5432',
                'candidate_address' => '456 Park Avenue, Petaling Jaya',
                'nationality' => 'Malaysian',
                'religion' => 'Buddhist',
                'job' => 'IT Consultant',
                'income' => 'RM 1000 - RM 2000',
                'marriage_status' => 'Married',
                'position' => 'Secretary',
                'short_biography' => 'Business strategist with strong community leadership background.',
                'manifesto' => 'Focus on economic growth and sustainable development.',
                'status' => 'Pending',
                'reason' => '',
                'sign' => 'candidate3.jpg',
                'votes_count' => 10,
                'user_id' => 2,
                'nominee_id' => json_encode([4]),
                'cand_doc_id' => json_encode([5,6]),
                'election_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'candidate_name' => 'Candidate 4',
                'candidate_image' => '',
                'candidate_phone' => '012-8765432',
                'candidate_email' => 'candidate4@example.com',
                'candidate_gender' => 'Male',
                'candidate_ic' => '900315-14-5432',
                'candidate_address' => '910 Park Avenue, Petaling Jaya',
                'nationality' => 'Malaysian',
                'religion' => 'Buddhist',
                'job' => 'IT Consultant',
                'income' => 'RM 2000 - RM 3000',
                'marriage_status' => 'Married',
                'position' => 'Secretary',
                'short_biography' => 'Business strategist with strong community leadership background.',
                'manifesto' => 'Focus on economic growth and sustainable development.',
                'status' => 'Pending',
                'reason' => '',
                'sign' => 'candidate4.jpg',
                'votes_count' => 20,
                'user_id' => 2,
                'nominee_id' => json_encode([4]),
                'cand_doc_id' => json_encode([1,4]),
                'election_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
} 